### ISSUE TITLE
Ability to display in reading order

### ISSUE THREAD

**Issue by SubJunk** [SubJunk/TimelineTools#70]
We already have the order but then use trickery to display in chronological order, so it should be easy to have a toggle to display in the order from the collections files

**Comment by polygirl** [comment]
Keen for your thoughts on how to display this in the UI.  Was thinking of changing the expanding panel when you change to this view so that it opens the selected comic centred in the expanded panel with the title above and a < > arrow for previous and next comic only, then display (slightly smaller) the previous two and next two comics like a carousel.  Similar to 
![image](https://user-images.githubusercontent.com/20376562/61349410-2afa3400-a8b8-11e9-98c0-63417174ff72.png)

**Comment by SubJunk** [comment]
With this issue I was more thinking of a main view change, as opposed to the expanded view - so right now they are displayed chronologically in that main view, but the idea I had was to have the ability to display in the reading order.
Your idea could be cool too but could have a different issue

**Comment by polygirl** [comment]
So we would lose the dates and have a dingle continuous stream? Would
series still hold a row or would they all be in a single row?

**Comment by SubJunk** [comment]
Good questions. It would be good to see it with the series still on the same row, to see how that looks. I think a lot of the existing logic would continue to work.

If you're going to have a go at it, I suggest thinking of dates as just numbers that can be incremented. 
So in this mode there could be one "year" with as many months as the total number of comics (just a number that increments with each comic), and then the dates up the top of the main screen are hidden. That's what I would try at first and see what happens.

**Comment by SubJunk** [comment]
@polygirl if you're still intending to work on this can you please assign yourself and set the pipeline?

**Comment by SubJunk** [comment]
@polygirl I'm gonna do that now, feel free to undo

**Comment by polygirl** [comment]
Merged
